spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://192.168.99.100:3307/CustomerService
    username: root
    password: mypassword
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8888


